export default {
  title: "Nosotros",
  info: {
    title: "La Web de los Tests de Inteligencia",
    description: {
      head1: "Entrenamiento online de aptitudes y habilidades mentales",
      text1:
        "bequiz.net ha sido creado para que los usuarios puedan entrenar sus aptitudes para oposiciones, entrevistas de trabajo, pero sobre todo, pueden considerarse como un conjunto de juegos de inteligencia.",
      head2: "¿Cómo realizar un test psicotécnico?",
      text2:
        "Atendiendo a diferentes niveles de dificultad y con una amplia variedad de preguntas y respuestas, podrás utilizar estas pruebas tanto para prepararte para el test psicotécnico que hacen en las oposiciones como para mejorar tus habilidades y capacidades mentales. Está comprobado cómo este tipo de test psicotécnico aumenta la capacidad intelectual de sus usuarios. Son pruebas a las que no has de tener miedo ya que todos, el que más o el que menos, tenemos aptitudes mentales para superarlas. Puede que algunos necesiten desarrollar aún más esta habilidad, por eso, cuantas más pruebas de estas realices, más posibilidades tendrás de mejorar y enriquecerte mentalmente. Para eso, se pone a tu disposición tests psicotécnicos gratis, realmente una gran variedad de estos. De esta manera, siempre que tengas un momento, podrás entrenar tu cerebro y cociente intelectual: puedes empezar por pruebas de memoria visual, conocimientos matemáticos y lingüísticos, test de cultura general… Si estás preparando unas oposiciones, piensa que este tipo de test psicotécnico es especial para ellas, igual que si estás a la espera de una entrevista de trabajo. Es muy importante aprender nuevos conocimientos y, sobre todo, tener agilidad mental. No hay otra forma de conseguirlo que trabajando diariamente. Además de la gratuidad de este tipo de test, destaca el factor tiempo. Simplemente tardarás unos minutos en realizarlos, pero te aseguramos que, si los haces diariamente, será suficiente para mejorar tu capacidad intelectual.",
      head3: "¿Por qué son tan populares los psicotécnicos?",
      text3:
        "Te puedes encontrar con un test psicotécnico para obtener una licencia de armas, para sacarte el carnet de conducir, o para opositar a según qué puestos. Su uso está muy extendido, al menos en los países desarrollados, y son una de las contribuciones que ha hecho la psicología a nuestra forma de vida. Todo empezó en Inglaterra, con un señor que se llamaba Francis Galton y en Francia, con Alfred Binet. Pronto se extendieron a los Estados Unidos, donde vieron que podrían ser un buen método para cribar soldados en la I Guerra Mundial. A medida que ha pasado el tiempo, la forma de hacer tests y cómo administrarlos ha evolucionado de la mano de una ciencia afín a la psicología: la psicometría. Los tests psicotécnicos se han perfeccionado hasta el punto de medir cosas muy diferentes.",
      head4: "¿Qué tipos hay?",
      text4:
        "Los hay de aptitud (tests de razonamiento numerico y verbal), que miden cómo te manejas con palabras, de forma oral y escrita, o con números. Por ejemplo, los test logico matematicos son parecidos a los que se usan en las empresas para selección de personal. -De aptitud espacial. Miden la capacidad de manejar mentalmente formas, volúmenes y objetos en tres dimensiones. -De razonamiento abstracto. Cómo utilizar la lógica para resolver problemas. -De atención y concentración. Tratan de medir la capacidad de mantener una tarea mientras realizas otra simultáneamente. -Los tests de memoria miden la capacidad de retener datos que hemos obtenido mediante la vista o el oído. -Por otro lado, tenemos los tests de personalidad. Puedes esperarte desde preguntas acerca de cómo te comportas normalmente. Los formatos de los test son de muchos tipos, desde dados, operaciones matemáticas, puzzles, tipo Raven, monedas, dominó, secuencias lógicas, palabras, letras, pasando por una variedad muy amplia de pruebas diferentes. Hacer tests psicotécnicos puede ser divertido y una buena forma de ejercitar tu mente a la vez que te familizarizas con ellos para cuando tengas un test psicotécnico en oposiciones. ¡Busca el tuyo y ponte a ello, son gratis!",
      head5: "¿Para qué pueden servir?",
      text5:
        "Los test psicotécnicos son ampliamente usados en las primeras fases de selección en el ámbito profesional. Miles de oposiciones a funcionario tienen tests de este tipo. Por ejemplo, oposiciones a policía local, policía nacional, bomberos, y en España también para la Guardia Civil o las policías autonómicas como los Mossos d'Esquadra, Ertzaintza, Policía Foral de Navarra etc, según la Comunidad Autónoma. Además, también suelen ser empleados en plazas y ascensos en marinería y tropa en el ejercito de tierra, aire y mar. Tampoco olvidemos las pruebas de selección de personal en las empresas más grande e incluso para puestos de responsabilidad. Muchos de estos opositores y academias han empleado nuestros tests para entrenarse y llegar al examen con mucha más confianza."
    }
  }
};
